default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("SCANBOX_USERNAME") %>
  password: <%= ENV.fetch("SCANBOX_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("SCANBOX_DATABASE") %>

test:
  <<: *default
  database: <%= ENV.fetch("SCANBOX_DATABASE_TEST") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("SCANBOX_DATABASE_PRODUCTION", "scanbox_db_prod") %>
  cable: &cable
    <<: *default
    database: scanbox_db_cable
  queue: &queue
    <<: *default
    database: scanbox_db_queue
  cache: &cache
    <<: *default
    database: scanbox_db_cache